version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5000"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - application

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - postgres
    networks:
      - application
networks:
  application: